/* The Daily Cactus — client-side renderer.
   Committed once, never regenerated by the routine. It fetches a day's edition
   JSON (just data) and builds the paper. Date picker + section nav are here, so
   the routine never writes HTML again. */

const $ = (sel) => document.querySelector(sel);

function esc(s) {
  return String(s == null ? "" : s)
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

// One story block. `lead` toggles the larger lead layout.
function storyHTML(s, lead = false) {
  const img = s.image
    ? `<img class="story-img" src="${esc(s.image)}" alt="" onerror="this.style.display='none'">`
    : "";
  const dev = s.developing ? `<span class="developing">📈 DEVELOPING</span>` : "";
  const take = s.takeaway
    ? `<p class="takeaway"><b>Key takeaway:</b> ${esc(s.takeaway)}</p>` : "";
  const why = s.why
    ? `<p class="why"><b>Why it matters:</b> ${esc(s.why)}</p>` : "";
  const url = esc(s.url || "#");
  return `<article${lead ? ' class="lead-article"' : ""}>
    ${img}${dev}
    <h2><a href="${url}" target="_blank" rel="noopener">${esc(s.headline)}</a></h2>
    <p class="summary">${esc(s.summary)}</p>
    ${take}${why}
    <p class="meta">${esc(s.source || "")} · <a href="${url}" target="_blank" rel="noopener">Read the original →</a></p>
  </article>`;
}

function oppHTML(o) {
  const url = esc(o.url || "#");
  const when = o.when ? `<p class="when">📅 ${esc(o.when)}</p>` : "";
  return `<article class="opp">
    <h2><a href="${url}" target="_blank" rel="noopener">${esc(o.name || o.headline)}</a></h2>
    ${when}
    <p class="summary">${esc(o.summary)}</p>
    <p class="meta">${esc(o.source || "")} · <a href="${url}" target="_blank" rel="noopener">Details →</a></p>
  </article>`;
}

function sectionBlock(name, slug, stories, beta = false) {
  if (!stories || !stories.length) return "";
  const tag = beta ? ` <span class="beta-tag">BETA</span>` : "";
  const note = beta
    ? `<p class="beta-note">Experimental — dates/details may be approximate; verify before relying on them.</p>`
    : "";
  const body = beta
    ? stories.map(oppHTML).join("")
    : stories.map((s) => storyHTML(s)).join("");
  return `<div class="grid" id="sec-${esc(slug)}">
    <h2 class="section-title">${esc(name)}${tag}</h2>
    ${note}${body}
  </div>`;
}

function renderEdition(ed) {
  // Dateline
  const d = new Date(ed.date + "T00:00:00");
  const nice = isNaN(d) ? ed.date
    : d.toLocaleDateString("en-IN", { weekday: "long", year: "numeric", month: "long", day: "numeric" });
  $("#dateline").textContent =
    `${nice} · Edition No. ${ed.edition ?? "—"} · Jaipur, India`;

  // Nav: Front Page + sections + Opportunities
  const navItems = [`<a data-target="top">Front Page</a>`];
  (ed.sections || []).forEach((s) =>
    navItems.push(`<a data-target="sec-${esc(s.slug)}">${esc(s.name)}</a>`));
  if (ed.opportunities && ed.opportunities.length)
    navItems.push(`<a data-target="sec-opportunities">Opportunities &amp; Events</a>`);
  $("#nav").innerHTML = navItems.join('<span class="sep">·</span>');
  $("#nav").querySelectorAll("a").forEach((a) =>
    a.addEventListener("click", () => {
      const t = a.getAttribute("data-target");
      if (t === "top") window.scrollTo({ top: 0, behavior: "smooth" });
      else document.getElementById(t)?.scrollIntoView({ behavior: "smooth" });
    }));

  // Body
  let html = "";
  if (ed.lead) html += `<section class="lead">${storyHTML(ed.lead, true)}</section>`;
  if (ed.frontpage && ed.frontpage.length)
    html += `<div class="grid">${ed.frontpage.map((s) => storyHTML(s)).join("")}</div>`;
  (ed.sections || []).forEach((s) =>
    html += sectionBlock(s.name, s.slug, s.stories));
  if (ed.opportunities && ed.opportunities.length)
    html += sectionBlock("Opportunities & Events", "opportunities", ed.opportunities, true);
  $("#paper").innerHTML = html;

  $("#colophon").textContent = ed.colophon || "";
}

async function loadEdition(date) {
  $("#paper").innerHTML = `<p class="status">Loading ${esc(date)}…</p>`;
  try {
    const r = await fetch(`editions/${date}.json`, { cache: "no-cache" });
    if (!r.ok) throw new Error(r.status);
    renderEdition(await r.json());
    const sel = $("#datepick");
    if (sel) sel.value = date;
    history.replaceState(null, "", `?date=${date}`);
  } catch (e) {
    $("#paper").innerHTML = `<p class="status">Couldn't load the ${esc(date)} edition.</p>`;
  }
}

async function init() {
  let manifest = { editions: [] };
  try {
    const r = await fetch("editions/index.json", { cache: "no-cache" });
    if (r.ok) manifest = await r.json();
  } catch (e) { /* no manifest yet */ }

  const eds = (manifest.editions || []).slice().sort((a, b) =>
    a.date < b.date ? 1 : -1); // newest first

  // Date picker
  if (eds.length) {
    const sel = $("#datepick");
    sel.innerHTML = eds.map((e) =>
      `<option value="${esc(e.date)}">${esc(e.date)}${e.lead ? " — " + esc(e.lead.slice(0, 60)) : ""}</option>`
    ).join("");
    sel.addEventListener("change", () => loadEdition(sel.value));
    $("#datebar").style.visibility = "visible";
  }

  // Which edition: ?date= param, else newest, else fail gracefully
  const param = new URLSearchParams(location.search).get("date");
  const start = param || (eds[0] && eds[0].date);
  if (start) loadEdition(start);
  else $("#paper").innerHTML = `<p class="status">No editions published yet. Check back after the next run.</p>`;
}

document.addEventListener("DOMContentLoaded", init);
