/* The Daily Cactus — "Cactus Craft" client-side renderer.
   Committed once, never regenerated by the routine. Fetches a day's edition
   JSON (data only) and builds the paper. All story content comes from
   untrusted RSS-derived feeds — every field is escaped before insertion.

   Story-id convention for thumbs / anchors (no id survives assembly onto the
   story object itself — see RENDERER_NOTES.md): derived as
   "<date>/<slug or 'front'>/<index>", where <index> is the story's position
   within its own scope (lead=0 in "front", frontpage continues after it,
   each section counts from 0, opportunities count from 0 in "opportunities").
   Brief anchors match by URL (the one field that survives both the brief
   item and the story it points to), not by that derived id. */

const $ = (sel) => document.querySelector(sel);

function esc(s) {
  return String(s == null ? "" : s)
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

// ---------- section colors (DESIGN_DIRECTION.md table) ----------
const SECTION_COLOR = {
  "ai": "clay",
  "deep-tech": "slate",
  "climate-energy": "leaf",
  "health-tech": "rose",
  "agritech": "olive",
  "indian-startups": "marigold",
  "india-deep-tech": "teal",
  "global-economics": "steel",
  "india": "saffron",
  "world": "horizon",
  "other-interests": "violet",
  "beyond-your-beat": "violet",
  "opportunities": "sea",
};
const COLOR_FALLBACK_ORDER = ["clay", "slate", "leaf", "rose", "olive", "marigold",
  "teal", "steel", "saffron", "horizon", "violet", "sea"];
function colorVar(slug) {
  if (SECTION_COLOR[slug]) return SECTION_COLOR[slug];
  // stable fallback for any future/unknown slug so nothing renders unstyled
  let h = 0;
  for (const c of String(slug || "")) h = (h * 31 + c.charCodeAt(0)) >>> 0;
  return COLOR_FALLBACK_ORDER[h % COLOR_FALLBACK_ORDER.length];
}

// pencil-rule seed variants (2-3, alternated across section heads — a 25-story guard)
const PENCIL_RULES = [
  { filter: "pencil", d: "M2 4.5 L 200 4 L 420 4.8 L 598 4.2" },
  { filter: "pencil-b", d: "M2 3.8 L 180 4.6 L 400 3.6 L 598 4.6" },
  { filter: "pencil-c", d: "M2 4.6 L 220 3.8 L 440 4.4 L 598 3.8" },
];

// ---------- image error handling (declared on window: inline onerror needs it) ----------
window.daily = window.daily || {};
window.daily.imgErr = function (img, isLead) {
  const fig = img.closest(".figure");
  if (!fig) return;
  if (isLead) {
    fig.classList.remove("tape");
    fig.innerHTML = cactusPlaceholderSVG();
  } else {
    fig.style.display = "none";
  }
};
window.daily.thumb = function (btn) {
  if (btn.dataset.sent === "1") return;
  const url = btn.dataset.href;
  btn.dataset.sent = "1";
  btn.classList.add("sent");
  btn.disabled = true;
  window.open(url, "_blank", "noopener");
};

function cactusPlaceholderSVG() {
  return `<svg viewBox="0 0 40 64" width="46" height="72" aria-hidden="true" opacity=".55" style="margin:auto">
    <use href="#cactus-doodle"/></svg><small>no photo</small>`;
}

// ---------- id derivation + GitHub issue links (B4 feedback loop) ----------
function storyId(date, scope, idx) {
  return `${date}/${scope}/${idx}`;
}
function issueURL(vote, id, headline, date) {
  const title = encodeURIComponent(`${vote === "up" ? "👍" : "👎"} ${id}`);
  const body = encodeURIComponent(`${headline || ""}\n\nEdition: ${date}`);
  return `https://github.com/amanbeni/daily-cactus/issues/new?labels=feedback&title=${title}&body=${body}`;
}
function thumbsHTML(id, headline, date) {
  const up = issueURL("up", id, headline, date);
  const dn = issueURL("down", id, headline, date);
  return `<span class="thumbs">
    <button aria-label="More like this" data-href="${esc(up)}" onclick="daily.thumb(this)">
      <svg viewBox="0 0 16 16"><use href="#thumb-up"/></svg></button>
    <button aria-label="Less like this" data-href="${esc(dn)}" onclick="daily.thumb(this)">
      <svg viewBox="0 0 16 16" style="transform:rotate(180deg)"><use href="#thumb-up"/></svg></button>
  </span>`;
}

// ---------- markets bar (B5) ----------
function fmtQuoteValue(q) {
  const v = typeof q.value === "number"
    ? q.value.toLocaleString("en-IN", { maximumFractionDigits: 2 })
    : esc(q.value);
  const unit = q.unit || "";
  if (unit === "₹") return `₹${v}`;
  if (unit.startsWith("₹") && unit.length > 1) return `₹${v}${esc(unit.slice(1))}`;  // ₹/10g, ₹/kg
  if (unit.startsWith("$") && unit.length > 1) return `$${v}${esc(unit.slice(1))}`;
  if (unit === "$") return `$${v}`;
  if (unit) return `${v}${esc(unit)}`;
  return v;
}
function marketsHTML(markets) {
  if (!markets || !Array.isArray(markets.quotes) || !markets.quotes.length) return "";
  return markets.quotes.map((q) => {
    const pct = typeof q.change_pct === "number" ? q.change_pct : null;
    const dir = pct == null ? "" : (pct >= 0 ? "up" : "dn");
    const pctTxt = pct == null ? "" : ` ${Math.abs(pct).toFixed(1)}%`;
    return `<span class="q ${dir}">${esc(q.label)} <b>${fmtQuoteValue(q)}${esc(pctTxt)}</b></span>`;
  }).join("");
}

// ---------- story-card pieces ----------
function figureHTML(s, lead) {
  if (s.image) {
    const err = lead ? "daily.imgErr(this,true)" : "daily.imgErr(this,false)";
    return `<div class="figure tape"><img src="${esc(s.image)}" alt="" loading="lazy" onerror="${err}"></div>`;
  }
  if (lead) return `<div class="figure">${cactusPlaceholderSVG()}</div>`;
  return "";
}

function keyStatHTML(s) {
  return s.key_stat ? `<span class="key-stat">${esc(s.key_stat)}</span>` : "";
}

function bodyHTML(s, tabVar) {
  let out = "";
  if (s.signal && s.signal.length) {
    out += `<div class="signal" style="--tabc:var(--${tabVar})"><b>The Signal</b><ul>${
      s.signal.map((b) => `<li>${esc(b)}</li>`).join("")}</ul></div>`;
  } else if (s.takeaway || s.why) {
    // legacy fallback (pre-Signal editions), restyled to Cactus Craft
    if (s.takeaway) out += `<p class="legacy-take"><b>Key takeaway&mdash;</b> ${esc(s.takeaway)}</p>`;
    if (s.why) out += `<div class="legacy-why" style="--tabc:var(--${tabVar})"><b>Why it matters</b>${esc(s.why)}</div>`;
  }
  if (s.editors_read) {
    out += `<div class="signal editors"><b>Editor&rsquo;s read</b>${esc(s.editors_read)}</div>`;
  }
  return out;
}

function alsoRailHTML(also) {
  if (!also || !also.length) return "";
  const items = also.map((a) => {
    const url = a.url ? esc(a.url) : "";
    const line = esc(a.line || "");
    const src = a.source ? ` <span style="opacity:.7">&mdash; ${esc(a.source)}</span>` : "";
    return url
      ? `<li><a class="sk" href="${url}" target="_blank" rel="noopener">${line}</a>${src}</li>`
      : `<li>${line}${src}</li>`;
  }).join("");
  return `<div class="also-rail"><h6>Also worth knowing</h6><ul>${items}</ul></div>`;
}

// Renders one story <article>. `opts`: {lead, slug, sectionName, id, showTab}
function storyCardHTML(s, opts) {
  const tabVar = colorVar(opts.slug);
  const tag = opts.lead ? "article" : "article";
  const cls = ["story", "card"];
  if (opts.lead) cls.push("lead-story");
  const kicker = [];
  if (opts.showTab !== false) {
    const row1 = [];
    if (opts.lead) {
      row1.push(`<span class="lead-badge">Lead<svg viewBox="0 0 80 34" aria-hidden="true"><use href="#lead-swash"/></svg></span>`);
    }
    if (opts.sectionName) row1.push(`<span class="tab" style="--tabc:var(--${tabVar})">${esc(opts.sectionName)}</span>`);
    if (s.developing) row1.push(`<span class="badge-dev">Developing</span>`);
    if (s.badge) row1.push(`<span class="badge-custom">${esc(s.badge)}</span>`);
    const row2 = s.source ? `<div class="row2">${esc(s.source)}</div>` : "";
    kicker.push(`<div class="kicker"><div class="row1">${row1.join("")}</div>${row2}</div>`);
  }
  const url = s.url ? esc(s.url) : "";
  const headlineHTML = url
    ? `<a href="${url}" target="_blank" rel="noopener" style="text-decoration:none;color:inherit">${esc(s.headline)}</a>`
    : esc(s.headline);
  const meta = `<div class="meta">${
      url ? `<a class="sk" href="${url}" target="_blank" rel="noopener">Read the original &rarr;</a>` : ""
    }${thumbsHTML(opts.id, s.headline, opts.date)}</div>`;

  const textBlock = `
        ${kicker.join("")}
        <h5>${headlineHTML}</h5>
        ${keyStatHTML(s)}
        <p class="summary">${esc(s.summary)}</p>
        ${bodyHTML(s, tabVar)}
        ${meta}`;

  if (opts.lead) {
    return `<${tag} class="${cls.join(" ")}" id="${esc(opts.anchorId)}" style="--tabc:var(--${tabVar})">
      <div>${textBlock}</div>
      ${figureHTML(s, true)}
    </${tag}>`;
  }
  return `<${tag} class="${cls.join(" ")}" id="${esc(opts.anchorId)}" style="--tabc:var(--${tabVar})">
    ${figureHTML(s, false)}
    ${textBlock}
  </${tag}>`;
}

function oppCardHTML(o, id) {
  const url = o.url ? esc(o.url) : "";
  const name = url
    ? `<a class="sk" href="${url}" target="_blank" rel="noopener">${esc(o.name)}</a>`
    : esc(o.name);
  const when = o.when ? `<span class="when">${esc(o.when)}</span>` : "";
  const src = o.source ? ` <span style="opacity:.7">&mdash; ${esc(o.source)}</span>` : "";
  return `<div class="opp card" id="${esc(id)}" style="--tabc:var(--sea)">
    ${when}<span>${name} &mdash; ${esc(o.summary)}${src}</span>
  </div>`;
}

function sectionHeadHTML(name, slug, ruleIdx) {
  const tabVar = colorVar(slug);
  const rule = PENCIL_RULES[ruleIdx % PENCIL_RULES.length];
  return `<div class="sec-head">
    <span class="tab" style="--tabc:var(--${tabVar})">${esc(name)}</span>
    <svg class="pencil-rule" viewBox="0 0 600 8" preserveAspectRatio="none" aria-hidden="true">
      <path d="${rule.d}" fill="none" stroke="#4E463C" stroke-width="1.5" stroke-linecap="round"
        opacity=".5" filter="url(#${rule.filter})"/></svg>
  </div>`;
}

// ---------- brief ----------
function normalizeBriefItems(brief) {
  if (!Array.isArray(brief)) return [];
  return brief.map((b) => (typeof b === "string" ? { line: b } : (b || {})));
}
function briefHTML(brief, urlAnchors) {
  const items = normalizeBriefItems(brief);
  if (!items.length) return "";
  const li = items.map((b) => {
    const line = esc(b.line || "");
    const anchor = b.url && urlAnchors.has(b.url) ? urlAnchors.get(b.url) : null;
    if (anchor) return `<li>${line} <a class="sk" href="#${esc(anchor)}">&darr; jump</a></li>`;
    if (b.url) return `<li>${line} <a class="sk" href="${esc(b.url)}" target="_blank" rel="noopener">&rarr;</a></li>`;
    return `<li>${line}</li>`;
  }).join("");
  return `<div class="card brief-card"><h4>The 2-minute brief</h4><ol>${li}</ol></div>`;
}

// ---------- main render ----------
function renderEdition(ed) {
  const date = ed.date || "";
  const d = new Date(date + "T00:00:00");
  const nice = isNaN(d) ? date
    : d.toLocaleDateString("en-IN", { weekday: "long", year: "numeric", month: "long", day: "numeric" });
  $("#dateline").innerHTML =
    `<span>${esc(nice)}</span> &middot; <span>Edition N&ordm; ${esc(ed.edition ?? "—")}</span> &middot; <span>Jaipur, India</span>`;

  $("#markets").innerHTML = marketsHTML(ed.markets);

  // Nav
  const navItems = [`<a data-target="top">Front Page</a>`];
  (ed.sections || []).forEach((s) => {
    if (s.stories && s.stories.length) navItems.push(`<a data-target="sec-${esc(s.slug)}">${esc(s.name)}</a>`);
  });
  if (ed.opportunities && ed.opportunities.length)
    navItems.push(`<a data-target="sec-opportunities">Opportunities</a>`);
  $("#nav").innerHTML = navItems.join('<span class="sep">&middot;</span>');
  $("#nav").querySelectorAll("a").forEach((a) =>
    a.addEventListener("click", () => {
      const t = a.getAttribute("data-target");
      if (t === "top") window.scrollTo({ top: 0, behavior: "smooth" });
      else document.getElementById(t)?.scrollIntoView({ behavior: "smooth" });
    }));

  // Pass 1: assign every story's derived id + collect a url -> anchor map for
  // brief links (the brief can't reference the story id directly — that id
  // does not survive scripts/assemble_edition.py onto the story object).
  const urlAnchors = new Map();
  const register = (s, anchorId) => { if (s && s.url && !urlAnchors.has(s.url)) urlAnchors.set(s.url, anchorId); };

  const leadId = ed.lead ? storyId(date, "front", 0) : null;
  if (ed.lead) register(ed.lead, leadId);
  const frontpageIds = (ed.frontpage || []).map((s, i) => storyId(date, "front", i + 1));
  (ed.frontpage || []).forEach((s, i) => register(s, frontpageIds[i]));
  // Feedback ids (for the 👍/👎 issue title) carry the story's HOME-SECTION slug
  // so fold_taste.py can attribute a front-page vote to a topic. These are
  // SEPARATE from the DOM/anchor ids above (which stay date/front/i for brief
  // jumps + nav). Falls back to "front" only when a lead has no home section.
  const leadFbId = ed.lead
    ? storyId(date, sectionSlugForFrontpage(ed, ed.lead) || "front", "lead") : null;
  const frontpageFbIds = (ed.frontpage || []).map((s, i) =>
    storyId(date, sectionSlugForFrontpage(ed, s) || "front", "fp" + (i + 1)));
  const sectionIds = (ed.sections || []).map((sec) =>
    (sec.stories || []).map((s, i) => storyId(date, sec.slug, i)));
  (ed.sections || []).forEach((sec, si) =>
    (sec.stories || []).forEach((s, i) => register(s, sectionIds[si][i])));
  const oppIds = (ed.opportunities || []).map((o, i) => storyId(date, "opportunities", i));

  // Pass 2: build HTML
  let html = "";
  html += briefHTML(ed.brief, urlAnchors);

  if (ed.lead || (ed.frontpage && ed.frontpage.length)) {
    html += `<div class="grid2">`;
    if (ed.lead) {
      html += storyCardHTML(ed.lead, { lead: true, slug: "front", sectionName: null, id: leadFbId, anchorId: leadId, date });
    }
    (ed.frontpage || []).forEach((s, i) => {
      html += storyCardHTML(s, { lead: false, slug: "front", sectionName: sectionNameForFrontpage(ed, s), id: frontpageFbIds[i], anchorId: frontpageIds[i], date });
    });
    html += `</div>`;
  }

  (ed.sections || []).forEach((sec, si) => {
    if (!sec.stories || !sec.stories.length) return;
    html += sectionHeadHTML(sec.name, sec.slug, si);
    html += `<div class="grid2" style="margin-top:16px">`;
    sec.stories.forEach((s, i) => {
      html += storyCardHTML(s, { lead: false, slug: sec.slug, sectionName: null, id: sectionIds[si][i], anchorId: sectionIds[si][i], date });
    });
    html += `</div>`;
    html += alsoRailHTML(sec.also);
  });

  if (ed.opportunities && ed.opportunities.length) {
    html += sectionHeadHTML("Opportunities & Events", "opportunities", (ed.sections || []).length);
    html += `<div id="sec-opportunities">`;
    ed.opportunities.forEach((o, i) => { html += oppCardHTML(o, oppIds[i]); });
    html += `</div>`;
  } else {
    // keep the anchor resolvable even when empty, harmless no-op div
  }

  $("#paper").innerHTML = html || `<p class="status">A quiet day &mdash; nothing cleared the bar.</p>`;

  // Section nav targets scroll to the section's head element (layout is a
  // flat sequence of card grids, not nested per-section containers).
  let secIdx = 0;
  (ed.sections || []).forEach((sec) => {
    if (!sec.stories || !sec.stories.length) return;
    const heads = document.querySelectorAll(".sec-head");
    if (heads[secIdx]) heads[secIdx].id = `sec-${sec.slug}`;
    secIdx++;
  });
  if (ed.opportunities && ed.opportunities.length) {
    const heads = document.querySelectorAll(".sec-head");
    if (heads[secIdx]) heads[secIdx].id = "sec-opportunities";
  }

  $("#colophon").innerHTML = `${esc(ed.colophon || "")} &middot; assembled by hand every morning
    <svg viewBox="0 0 40 64" aria-hidden="true"><use href="#cactus-doodle"/></svg>`;
}

// Best-effort section name for a frontpage story (frontpage stories carry no
// slug of their own in the schema; look them up by url against the sections).
function sectionNameForFrontpage(ed, story) {
  for (const sec of ed.sections || []) {
    for (const s of sec.stories || []) {
      if (s.url && story.url && s.url === story.url) return sec.name;
    }
  }
  return null;
}

// Home-section SLUG for a lead/frontpage story (matched by url), for the
// feedback id so votes on front-page stories map to a topic. Null if unmatched.
function sectionSlugForFrontpage(ed, story) {
  for (const sec of ed.sections || []) {
    for (const s of sec.stories || []) {
      if (s.url && story.url && s.url === story.url) return sec.slug;
    }
  }
  return null;
}

async function loadEdition(date) {
  $("#paper").innerHTML = `<p class="status">Loading ${esc(date)}&hellip;</p>`;
  try {
    const path = date === "__fixture__" ? "dev-fixture.json" : `editions/${date}.json`;
    const r = await fetch(path, { cache: "no-cache" });
    if (!r.ok) throw new Error(r.status);
    const ed = await r.json();
    renderEdition(ed);
    const sel = $("#datepick");
    if (sel && date !== "__fixture__") sel.value = date;
    if (date !== "__fixture__") history.replaceState(null, "", `?date=${date}`);
  } catch (e) {
    $("#paper").innerHTML = `<p class="status">Couldn't load the ${esc(date)} edition.</p>`;
  }
}

async function init() {
  // Dev-only fixture path — harmless in prod, never linked from the UI.
  const params = new URLSearchParams(location.search);
  if (params.get("fixture") === "1") {
    $("#datebar").style.visibility = "hidden";
    loadEdition("__fixture__");
    setupKeyboardNav();
    return;
  }

  let manifest = { editions: [] };
  try {
    const r = await fetch("editions/index.json", { cache: "no-cache" });
    if (r.ok) manifest = await r.json();
  } catch (e) { /* no manifest yet */ }

  const eds = (manifest.editions || []).slice().sort((a, b) =>
    a.date < b.date ? 1 : -1); // newest first

  if (eds.length) {
    const sel = $("#datepick");
    sel.innerHTML = eds.map((e) =>
      `<option value="${esc(e.date)}">${esc(e.date)}${e.lead ? " — " + esc(e.lead.slice(0, 60)) : ""}</option>`
    ).join("");
    sel.addEventListener("change", () => loadEdition(sel.value));
    $("#datebar").style.visibility = "visible";
  }

  const param = params.get("date");
  const start = param || (eds[0] && eds[0].date);
  if (start) loadEdition(start);
  else $("#paper").innerHTML = `<p class="status">No editions published yet. Check back after the next run.</p>`;

  setupKeyboardNav();
}

// keyboard j/k to jump between story cards
function setupKeyboardNav() {
  let idx = -1;
  document.addEventListener("keydown", (e) => {
    const tag = (document.activeElement && document.activeElement.tagName) || "";
    if (tag === "SELECT" || tag === "INPUT" || tag === "TEXTAREA") return;
    if (e.key !== "j" && e.key !== "k") return;
    const cards = Array.from(document.querySelectorAll(".story"));
    if (!cards.length) return;
    idx = e.key === "j" ? Math.min(idx + 1, cards.length - 1) : Math.max(idx - 1, 0);
    cards[idx].scrollIntoView({ behavior: "smooth", block: "center" });
  });
}

document.addEventListener("DOMContentLoaded", init);
